name: Update Badges

on:
  push:
    branches: [ main ]
  schedule:
    # Update badges daily at 2 AM UTC
    - cron: '0 2 * * *'

jobs:
  update-badges:
    name: Update README Badges
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./tinybase-mockup

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: ./tinybase-mockup/package-lock.json

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Run tests with coverage
        run: npm run test:coverage

      - name: Generate test badge
        uses: badge-generator/vitest-badge@v1
        with:
          coverage-file: ./tinybase-mockup/coverage/coverage-summary.json
          badge-path: ./.github/badges/tests.svg

      - name: Generate coverage badge  
        uses: badge-generator/javascript-coverage-badge@main
        with:
          coverage-file: ./tinybase-mockup/coverage/coverage-summary.json
          badge-path: ./.github/badges/coverage.svg

      - name: Generate build status badge
        working-directory: ./
        run: |
          mkdir -p ./.github/badges
          # This will be updated by the CI workflow
          echo "Build status badge will be generated by CI"

      - name: Commit badges
        working-directory: ./
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .github/badges/
          git diff --staged --quiet || git commit -m "Update badges [skip ci]"
          git push

  lighthouse:
    name: Lighthouse Performance
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./tinybase-mockup

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: ./tinybase-mockup/package-lock.json

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Setup Expo CLI
        run: npm install -g @expo/cli

      - name: Build for web
        run: expo export -p web --output-dir lighthouse-build
        env:
          EXPO_NO_TELEMETRY: 1

      - name: Serve built app
        run: |
          npm install -g serve
          serve -s lighthouse-build -p 3000 &
          sleep 10

      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@v10
        with:
          configPath: './tinybase-mockup/.lighthouserc.json'
          uploadArtifacts: true
          temporaryPublicStorage: true

  bundle-analysis:
    name: Bundle Size Analysis
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./tinybase-mockup

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: ./tinybase-mockup/package-lock.json

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Analyze bundle size
        run: |
          npm install -g @expo/cli
          expo export -p web --output-dir bundle-analysis
          
          # Generate bundle report
          echo "📦 Bundle Size Analysis" > bundle-report.txt
          echo "======================" >> bundle-report.txt
          du -sh bundle-analysis/ >> bundle-report.txt
          echo "" >> bundle-report.txt
          echo "Detailed breakdown:" >> bundle-report.txt
          find bundle-analysis -name "*.js" -exec ls -lh {} \; | head -20 >> bundle-report.txt

      - name: Upload bundle analysis
        uses: actions/upload-artifact@v4
        with:
          name: bundle-analysis
          path: |
            bundle-analysis/
            bundle-report.txt